---
- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
#    - unsupported.yml
