# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    # This should work fine on Ubuntu 20.04 and 22.04. Lastest is currently on 20.04
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Update system packages and install ansible
        run: |
          apt update
          apt upgrade -y
          python3 -m pip -V
          python3 -m pip install ansible
          ansible --version
